
```{r}
#install.packages(c("lme4","juliaCall","multcomp","dplyr"))
library(JuliaCall)
j = julia_setup(installJulia = TRUE)
```

```{julia}
using Pkg
Pkg.activate(".")
Pkg.add(["MixedModels","JellyMe4","RCall"])
  
ENV["LMER"] ="lmerTest::lmer"
```

```{r}
data_dwelltime = read.csv("../data/2024-07-23_data-dwelltime.csv")
data_entrytime = read.csv("../data/2024-07-23_data-entrytime.csv")
data_entrytime$participant = data_dwelltime$participant

data_entrytime$rt = data_entrytime$first_entry_time_left

ix_right = is.na(data_entrytime$first_entry_time_left)
data_entrytime$rt[ix_right] = data_entrytime$first_entry_time_right[ix_right]

data_entrytime$response = data_entrytime$first_entry_ID_left
data_entrytime$response[ix_right] = data_entrytime$first_entry_ID_right[ix_right]

# stim effects
data_entrytime$ocd_left = data_entrytime$stim_ocd == -1
data_entrytime$ocd_right = data_entrytime$stim_ocd == 1

data_entrytime$pho_left = data_entrytime$stim_pho == -1
data_entrytime$pho_right = data_entrytime$stim_pho == 1

data_entrytime$neg_left = data_entrytime$stim_neg == -1
data_entrytime$neg_right = data_entrytime$stim_neg == 1

data_entrytime$looked_right = is.na(data_entrytime$first_entry_ID_left)
ir = data_entrytime$looked_right
il = !data_entrytime$looked_right
data_entrytime$looked_at = 'neutral'
data_entrytime$not_looked_at = 'neutral'

ix = (il & data_entrytime$pho_left) | (ir & data_entrytime$pho_right)
data_entrytime$looked_at[ix] = "pho"

ix = (il & data_entrytime$ocd_left) | (ir & data_entrytime$ocd_right)
data_entrytime$looked_at[ix] = "ocd"

ix = (il & data_entrytime$neg_left) | (ir & data_entrytime$neg_right)
data_entrytime$looked_at[ix] = "neg"

ix = (ir & data_entrytime$pho_left) | (il & data_entrytime$pho_right)
data_entrytime$not_looked_at[ix] = "pho"

ix = (ir & data_entrytime$ocd_left) | (il & data_entrytime$ocd_right)
data_entrytime$not_looked_at[ix] = "ocd"

ix = (ir & data_entrytime$neg_left) | (il & data_entrytime$neg_right)
data_entrytime$not_looked_at[ix] = "neg"


```

```{r}
library(dplyr)

library(lme4)
library(multcomp)
library(lmerTest)
```
```{r multilevel model}

data_dwelltime$group <- relevel(as.factor(data_dwelltime$group),ref = "healthy")

mlm_dwelltime <- lmer(dwell_diff ~ group + stim_ocd + stim_pho + stim_neg  + group:stim_ocd + group:stim_pho + group:stim_neg +
                        (1 + stim_ocd + stim_pho + stim_neg || participant),
                        #(1 + group | picture_pair_countingindex),
                      data = data_dwelltime,
                      REML=TRUE,
                      control = lmerControl(), # default optimiser
                      set.seed(1337)) # set the seed to replicate results
summary(mlm_dwelltime)
```

```{R}
# find ID <-> group mapping
df = data_dwelltime%>%select(participant,group)%>%unique()

# extract the individual participant coefficient for the OCD stim effect
df$stim_ocd = coef(mlm_dwelltime)$participant$stim_ocd + coef(mlm_dwelltime)$participant$groupocd + coef(mlm_dwelltime)$participant$`groupocd:stim_ocd`
df
```
```{julia}
using RCall
using MixedModels
using JellyMe4
jl_data_entrytime = @rget data_entrytime

rt_form= @formula(rt ~ group*looked_at + looked_right*group+zerocorr(1 +looked_at+looked_right| participant))


tmp = fit(MixedModel, rt_form, jl_data_entrytime;contrasts=Dict(:group=>DummyCoding(;base="healthy"),
                                                                :looked_right=>EffectsCoding(),
                                                                :looked_at=>DummyCoding(;base="neutral")));

#tupl = (tmp,jl_data_entrytime);
#@rput(tupl);
```
```{julia}
typeof(tpl)
```
```{julia}
tpl = (tmp,jl_data_entrytime)
@rput(tpl)
```

```{R}
#j$assign("form", formula(mlm_dwelltime))
j$assign("jl_data_dwelltime", data_dwelltime)
j$assign("jl_data_entrytime", data_entrytime)
julia_command("jl_data_entrytime.response .= jl_data_entrytime.response .-1")
julia_command("using MixedModels")
julia_command("using JellyMe4")

julia_command("form_triplet = @formula(dwell_diff ~ group + stim_ocd + stim_pho + stim_neg  + group&stim_ocd + group&stim_pho + group&stim_neg + 
              (1 + stim_ocd + stim_pho + stim_neg | triplet)+
              (1 + stim_ocd + stim_pho + stim_neg | participant) +
              (1 + group | picture_pair_countingindex))")


julia_command("form_only_triplet = @formula(dwell_diff ~ group + stim_ocd + stim_pho + stim_neg  + group&stim_ocd + group&stim_pho + group&stim_neg + 
              (1 + stim_ocd + stim_pho + stim_neg | triplet)+
              zerocorr(1 + group | picture_pair_countingindex))")

julia_command("form_triplet_zerocorr = @formula(dwell_diff ~ group + stim_ocd + stim_pho + stim_neg  + group&stim_ocd + group&stim_pho + group&stim_neg + 
              zerocorr(1 + stim_ocd + stim_pho + stim_neg | triplet)+
              (1 + stim_ocd + stim_pho + stim_neg | participant) +
              zerocorr(1 + group | picture_pair_countingindex))")

julia_command("form_zerocorr = @formula(dwell_diff ~ group + stim_ocd + stim_pho + stim_neg  + group&stim_ocd + group&stim_pho + group&stim_neg + 
              (1| picture_pair_countingindex)+
              (1 + stim_ocd + stim_pho + stim_neg | participant))")

julia_command("form = @formula(dwell_diff ~ group + stim_ocd + stim_pho + stim_neg  + group&stim_ocd + group&stim_pho + group&stim_neg + 
              zerocorr(1 + stim_ocd + stim_pho + stim_neg | triplet)+
              (1 + stim_ocd + stim_pho + stim_neg | participant))")

j$eval("fm_trip = fit(LinearMixedModel, form_triplet, jl_data_dwelltime)")
j$eval("fm_trip_zc = fit(LinearMixedModel, form_triplet_zerocorr, jl_data_dwelltime)")

j$eval("fm_zc = fit(LinearMixedModel, form_zerocorr, jl_data_dwelltime)")
j$eval("fm_only_triplet = fit(LinearMixedModel, form_only_triplet, jl_data_dwelltime)")


julia_command("glm_form= @formula(response ~ group + stim_ocd + stim_pho + stim_neg  + group&stim_ocd + group&stim_pho + group&stim_neg + 
              zerocorr(1 + stim_ocd + stim_pho + stim_neg | participant))")

j$eval("glm_part = fit(MixedModel, glm_form, jl_data_entrytime,Bernoulli();contrasts=Dict(:group=>DummyCoding(;base=\"healthy\")))")

julia_command("rt_form= @formula(rt ~ group*looked_at + looked_right*group+
              zerocorr(1 +looked_at+looked_right| participant))")


julia_command("tmp = fit(MixedModel, rt_form, jl_data_entrytime;contrasts=Dict(
       :group=>DummyCoding(;base=\"healthy\"),:looked_right=>EffectsCoding(),:looked_at=>DummyCoding(;base=\"neutral\")));")

julia_command("tupl = (tmp,jl_data_entrytime);")
j$eval("@rput(tupl);")
j$eval("typeof(tupl)")

```
# Test of Hypotheses Based on Multilevel Model
To establish contrast codes that directly test the hypotheses, we first code the hypotheses we want to test. Then, we fit the established effects in the contrast() function. This function allows direct inspection of effects. The p-values are estimated by the Kenward-Roger method. The p-values are unadjusted.

```{r generalised hypotheses matrices}
# Define the model comparisons to test the specific hypothesis of hypothesis 2
g = (glht(mlm_dwelltime, (c("groupocd:stim_ocd - groupocd = 0", # Patients with OCD look at idiosyncratic OCD-relevant material longer compared to neutral material (maintenance bias within group)
                            "groupocd:stim_ocd - groupocd:stim_neg = 0", # Patients with OCD look at idiosyncratic OCD-relevant material longer compared to negative material (maintenance bias within group)
                            "groupocd:stim_ocd - stim_ocd = 0", # Patients with OCD will show a more pronounced maintenance bias compared to healthy participants (maintenance bias between groups)
                            "groupocd:stim_ocd -  groupspider:stim_pho = 0" # Patients with OCD will show a more pronounced maintenance to idiosyncratic disorder-specific material compared to patients with spider phobia (maintenance bias between group)
))))

# Kenward-Roger is a more conservative method than the likelihood ratio test 
# Likelihood ratio tests always compares two models with each other 
# this is easy when the contrast is a treatment effect, but more difficult if we have three variables
# Deviation from preregistration - but this option is better, as 
# 1. Contrasts are more easily to be implemented with contest(), as we have many different contrasts and three groups that we want to compare within- and between-subjects (LR would only allow two comparisons at a time)
# 2. Kenward-Roger is more conservative than Likelihood Ratio Test
contest(mlm_dwelltime,g$linfct,joint=FALSE)#,ddf="Kenward-Roger")
```


```{r}
library(fddm)
library(tidyr)



bla = function(d){

  #d = df[Z==z]
#d = data_entrytime


d = d%>%subset(rt>=50)
fit0 <- ddm(rt + response ~ 1+ocd_left+ocd_right+pho_left+pho_right+neg_left+neg_right, data = d)
return(data.frame(t(coef(fit0))))
}
drift_res = data_entrytime %>% drop_na(stim_pho,stim_ocd) %>% group_by(participant,group) %>% do(bla(.))


```